version: '3.9'

services:
  ecea_server:
    image: ecea-api
    container_name: ecea-api
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
    environment:
        - DB_PORT=${POSTGRES_PORT}
        - DB_HOST=${POSTGRES_HOST}
    restart: always
    ports:
      - ${SERVER_EXTERNAL_PORT}:${SERVER_EXTERNAL_PORT}
    depends_on:
      - ecea_db
    volumes:
      - .:/app
      - ./static:/static

  ecea_db:
    image: postgres
    container_name: ecea-db
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}
    volumes:
      - ./database:/data/postgres

  adminer:
    image: adminer
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}