version: '3.9'

services:
  app:
    image: probe-22-server
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'probe_22'
      MYSQL_USER: 'probe'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes: 
      - ./docker-mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80