version: '3.9'

services:
  app:
    image: probe-22-server
    build: .
    restart: always
    ports:
      - ${SERVER_EXTERNAL_PORT}:3000
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysqldb
    restart: unless-stopped
    env_file:
      - .env
    volumes: 
      - ./docker-mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_EXTERNAL_PORT}:80